name: "Deploy Site VPS"
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Copiar arquivos para VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "."
          exclude: |
            .git*
          target: "/var/www/html/fidelitystore-site"

      - name: Reiniciar servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            set -e
            # Navega para o diretório do projeto
            cd /var/www/html/fidelitystore-site
            
            # Reinicia o Apache para servir os novos arquivos
            echo ">>> Reiniciando o servidor Apache..."
            sudo systemctl restart apache2
            
            echo ">>> Deploy finalizado com sucesso!"